### ISSUE TITLE
exception of ReadAclsById twice.

### ISSUE THREAD

**Issue by knownact** [RovoMe/spring-security-acl-mongodb#3]
unit test is a little modification from another test, I just want to compare result of two readAclsById, but get the exception.
```java
    @Test
    @WithMockUser
    public void testReadAclsByIdTwice() throws Exception {
        // Arrange
        TestDomainObject domainObject = new TestDomainObject();
        TestDomainObject firstObject = new TestDomainObject();
        TestDomainObject secondObject = new TestDomainObject();
        TestDomainObject thirdObject = new TestDomainObject();
        TestDomainObject unrelatedObject = new TestDomainObject();

        ObjectIdentity objectIdentity = new ObjectIdentityImpl(Class.forName(domainObject.getClass().getName()), domainObject.getId());

        MongoAcl parent = new MongoAcl(domainObject.getId(), domainObject.getClass().getName(), UUID.randomUUID().toString(),"owner", null, true);
        MongoAcl child1 = new MongoAcl(firstObject.getId(), firstObject.getClass().getName(), UUID.randomUUID().toString(), "Tim Test", parent.getId(), true);
        MongoAcl child2 = new MongoAcl(secondObject.getId(), secondObject.getClass().getName(), UUID.randomUUID().toString(), "Petty Pattern", parent.getId(), true);
        MongoAcl child3 = new MongoAcl(thirdObject.getId(), thirdObject.getClass().getName(), UUID.randomUUID().toString(), "Sam Sample", parent.getId(), true);
        MongoAcl nonChild = new MongoAcl(unrelatedObject.getId(), unrelatedObject.getClass().getName(), UUID.randomUUID().toString());

        DomainObjectPermission permission = new DomainObjectPermission(UUID.randomUUID().toString(),
            "user-0",
            BasePermission.READ.getMask() | BasePermission.WRITE.getMask(),
            true, true, true);

        parent.getPermissions().add(permission);
        child1.getPermissions().add(permission);
        child2.getPermissions().add(permission);

        // MongoAcl must has owner

        aclRepository.save(parent);
        aclRepository.save(child1);
        aclRepository.save(child2);
        aclRepository.save(child3);
        aclRepository.save(nonChild);

        // Act
        List<Sid> sids = new LinkedList<>();
        sids.add(new PrincipalSid("user-0"));

        List<Sid> sids1 = new LinkedList<>();
        sids.add(new PrincipalSid("owner"));

        //List<ObjectIdentity> childObjects = aclService.findChildren(objectIdentity);
        List<ObjectIdentity> childObjects = aclService.findChildren(objectIdentity);

        //Map<ObjectIdentity, Acl> resultOwner = aclService.readAclsById(childObjects, sids1);
        Map<ObjectIdentity, Acl> resultUser = aclService.readAclsById(childObjects, sids);

        // Assert
        assertThat(childObjects.size(), is(equalTo(3)));
        assertThat(resultUser.keySet().size(), is(equalTo(3)));
        resultUser.values().removeIf(Objects::isNull);
        resultUser.keySet().forEach(objectIdentity1 -> {
            Acl acl = resultUser.get(objectIdentity1);
            System.out.println("ACE Size found: " + acl.getEntries().size());
        });
        assertThat(resultUser.keySet().size(), is(equalTo(3)));
    }
```
The Exception is:
```java
java.lang.IllegalStateException: Error: SID-filtered element detected when implementation does not perform SID filtering - have you added something to the cache manually?

	at org.springframework.security.acls.mongodb.BasicLookupStrategy.readAclsById(BasicLookupStrategy.java:122)
	at org.springframework.security.acls.mongodb.MongoDBAclService.readAclsById(MongoDBAclService.java:96)
	at io.pinzi.security.AclUnitTest.testReadAclsByIdTwice(AclUnitTest.java:458)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

The strange thing is , if I comment anyone of next two lines, the code works ok:
```java
        //Map<ObjectIdentity, Acl> resultOwner = aclService.readAclsById(childObjects, sids1);
        Map<ObjectIdentity, Acl> resultUser = aclService.readAclsById(childObjects, sids);
```

**Comment by knownact** [comment]
I found that clear cache between readAclsById is working, 
```java
Map<ObjectIdentity, Acl> resultOwner = aclService.readAclsById(childObjects, sids1);
aclCache.clearCache();
Map<ObjectIdentity, Acl> resultUser = aclService.readAclsById(childObjects, sids);
```

**Comment by RovoMe** [comment]
First, your test here adds both sids to the same list leaving the other empty. I guess you meant to add the second principal `owner` to the second list.

The exception here is a bit cumbersome to explain. In short, the ACL was created with a list of loaded Sids, which by mistake was the list provided on invocation time. As the generated ACL is stored in the local cache, on the second invocation the ACL was retrieved from the cache and a check on the loaded Sids was performed. As the first invocation did specify an other set of sids compared to the second invocation, the service thought the ACLs were modified and thus threw the exception due to an illeagal state.

As to my understanding the list of loaded Sids is only used to check which Sids have yet to be loaded from the database (this affects only SQL databases; In the MongoDB case we do store the Sids within the ACL itself and thus do not have to load them later), instead of passing in a wrong list of Sids, I should have passed in null which tells the ACL instance that no check for sids has to be performed. This happens now and thus should prevent the exception.

In order to return only ACLs which match any of the given sids,  I've now added two more methods that check if the converted ACL does either declare an owner matching any of the provided security identities or if the permissions declare a target equal to any sids provided. If the ACL itself does not define any of these and a parent is available and the inheriting flag is set to true the same checks will be performed against the parent (and its ancestors). The ACL is only added to the result now, if it self or one of its ancestor (with the inherit flag set to true) specify at least a one permission or owner matching any identity contained in the list of sids.

Hope this all makes sense
